---

name: Blank Workflow
# on: [push, pull_request, workflow_dispatch]
on: [workflow_dispatch]
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo "Checkout done!"

  action1:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - name: Action 1
        run: echo "action1 after checkout"

  action2:
    runs-on: ubuntu-latest
    steps:
      - name: Action 2
        run: echo "action2"
